package com.brenda.ops;

import org.openide.util.Task;

import java.sql.SQLException;

public class CalculateCost extends Task {
    public static void main(String args[])
            throws SQLException, ClassNotFoundException {
//        String driverClassName
//                = "com.mysql.jdbc.Driver";
//        String url = "jdbc:mysql://localhost/toys";
//        String username = "root";
//        String password = "new_password";
//        String query
//                = "SELECT  SUM(price*quantity) totals FROM toys_table WHERE name = 'name' ";
//
//        // Load driver class
//        Class.forName(driverClassName);
//
//        // Obtain a connection
//        Connection con = DriverManager.getConnection(
//                url, username, password);
//
//        // Obtain a statement
//        Statement st = con.createStatement();
//
//        // Execute the query
//        int count = st.executeUpdate(query);
//        System.out.println(
//                "number of rows affected by this query= "
//                        + count);
//
//        // Closing the connection as per the
//        // requirement with connection is completed
//        con.close();
    }
}